---
version: '3'

metadata:
  package:
    download: '{{.REPO}}/releases/download/v{{.TAG}}/Models-{{.TAG}}-{{.PLATFORM_ARCH}}.zip'
    file: 'examples/models/build/_dist/Models-{{.PACKAGE_VERSION}}-{{.PLATFORM_ARCH}}.zip'
  container:
    repository: ghcr.io/boschglobal/dse-sdp

  models:
    Simple:
      name: Simple
      displayName: Simple
      path: simple
      workflows:
        - printfile
        - message
        - download
      platforms:
        - linux-amd64
        - linux-x86
        - linux-i386
      channels:
        - alias: signal
    Gateway:
      name: Gateway
      displayName: Gateway
      path: gateway
      workflows:
        - printfile
      platforms:
        - linux-amd64
      channels:
        - alias: signal
    Network_CAN:
      name: Network_CAN
      displayName: Network_CAN
      path: network_can
      workflows: []
      platforms:
        - linux-amd64
        - linux-x86
        - windows-x64
        - windows-x86
      channels:
        - alias: binary
    Network_PDU:
      name: Network_PDU
      displayName: Network_PDU
      path: network_pdu
      workflows: []
      platforms:
        - linux-amd64
        - linux-x86
        - windows-x64
        - windows-x86
      channels:
        - alias: binary
vars:
  # When running from E2E tests (i.e. Docker in Docker), the SDP_SIMDIR (for
  # Docker commands) must be set to the host relative path.
  SDP_SIMDIR: '{{if .SIM}}{{.ENTRYWORKDIR}}/{{.SIM}}{{else}}{{.PWD}}{{end}}'
  # Container image specification.
  SDP_REPO: 'https://github.com/boschglobal/dse.sdp'
  SDP_REGISTRY: ghcr.io/boschglobal
  SDP_IMAGE: '{{if .SDP_IMAGE}}{{.SDP_IMAGE}}{{else}}{{.SDP_REGISTRY}}/dse-sdp:{{.TAG | default "latest"}}{{end}}'
  SDP_USER:
    sh: id -u
  SDP_GROUP:
    sh: id -g

tasks:
  info:
    run: always
    silent: true
    dir: '{{.USER_WORKING_DIR}}'
    label: dse:sdp:info
    cmds:
      - echo "=== Taskfile global (SDP Namespace) ==="
      - echo SDP_SIMDIR={{.SDP_SIMDIR}}
      - echo SDP_IMAGE={{.SDP_IMAGE}}
      - echo SDP_USER={{.SDP_USER}}
      - echo SDP_GROUP={{.SDP_GROUP}}
      - echo "=== Taskfile Include ==="
      - echo ENTRYWORKDIR={{.ENTRYWORKDIR}}
      - echo SIM={{.SIM}}
      - echo TAG={{.TAG}}
      - echo "=== Runtime/Other ==="
      - echo PACKAGE_VERSION={{.PACKAGE_VERSION}}
      - echo PLATFORM_ARCH={{.PLATFORM_ARCH}}
      - echo USER_WORKING_DIR={{.USER_WORKING_DIR}}

  message:
    run: always
    dir: '{{.USER_WORKING_DIR}}'
    label: dse:sdp:message
    cmds:
      - echo "MSG={{.MSG}}"
    requires:
      vars: [MSG]

  printfile:
    desc: Print contents of a file
    run: when_changed
    dir: '{{.USER_WORKING_DIR}}'
    label: dse:sdp:printfile
    cmds:
      - cat "{{.OUTDIR}}/{{.FILE}}"
    requires:
      vars: [FILE]

  download:
    desc: downloads remote url file without auth
    run: when_changed
    dir: '{{.USER_WORKING_DIR}}'
    label: dse:sdp:download
    cmds:
      - cd {{.OUTDIR}}/downloads && curl -L -O "{{.URL}}"
    requires:
      vars: [URL]

  write-message:
    desc: write message to a file in the specified path
    run: when_changed
    dir: '{{.USER_WORKING_DIR}}'
    label: dse:sdp:write-message
    cmds:
      - mkdir -p "{{.PATH}}"
      - echo "{{.MESSAGE}}" > "{{.PATH}}/{{.FILE}}"
      - cat "{{.PATH}}/{{.FILE}}"
    requires:
      vars: [PATH, FILE, MESSAGE]
