---
version: '3'

metadata:
  package:
    download: '{{.REPO}}/releases/download/v{{.TAG}}/Models-{{.TAG}}-{{.PLATFORM_ARCH}}.zip'
    file: 'examples/models/build/_dist/Models-0.0.1-linux-amd64.zip'
  container:
    repository: ghcr.io/boschglobal/dse-sdp

  models:
    Simple:
      name: Simple
      displayName: Simple
      path: simple
      workflows:
        - filedownload
        - message
      platforms:
        - linux-amd64
        - linux-x86
        - linux-i386
      channels:
        - alias: signal
    Gateway:
      name: Gateway
      displayName: Gateway
      path: gateway
      workflows:
        - filedownload
      platforms:
        - linux-amd64
      channels:
        - alias: signal
    Network_CAN:
      name: Network_CAN
      displayName: Network_CAN
      path: network_can
      workflows: []
      platforms:
        - linux-amd64
        - linux-x86
        - windows-x64
        - windows-x86
      channels:
        - alias: binary
    Network_PDU:
      name: Network_PDU
      displayName: Network_PDU
      path: network_pdu
      workflows: []
      platforms:
        - linux-amd64
        - linux-x86
        - windows-x64
        - windows-x86
      channels:
        - alias: binary
vars:
  # When running from E2E tests (i.e. Docker in Docker), the ENTRYDIR (for
  # Docker commands) must be set to the host relative path.
  ENTRYDIR: '{{if .SIM}}{{.ENTRYWORKDIR}}/{{.SIM}}{{else}}{{.PWD}}{{end}}'
  # Container image specification.
  SDP_IMAGE: '{{.SDP_IMAGE | default "ghcr.io/boschglobal/dse-sdp"}}'
  IMAGE_TAG: '{{if .SDP_TAG}}{{.SDP_TAG}}{{else}}{{if .IMAGE_TAG}}{{.IMAGE_TAG}}{{else}}latest{{end}}{{end}}'

tasks:

  info:
    run: always
    dir: '{{.USER_WORKING_DIR}}'
    label: dse:sdp:info
    cmds:
      - echo "{{.ENTRYDIR}}"
      - echo "{{.SDP_IMAGE}}"
      - echo "{{.IMAGE_TAG}}"

  message:
    run: always
    dir: '{{.USER_WORKING_DIR}}'
    label: dse:sdp:message
    cmds:
      - echo "MSG={{.MSG}}"
    requires:
      vars: [MSG]

  filedownload:
    desc: Print contents of downloaded file
    run: when_changed
    dir: '{{.USER_WORKING_DIR}}'
    label: dse:sdp:filedownload
    cmds:
      - cat "{{.USER_WORKING_DIR}}/{{.OUTDIR}}/{{.FILE}}"
    requires:
      vars: [FILE]
