/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 0.1.dev1+g32ca81e Thu Dec 12 04:52:19 2024.
 */

#ifndef BRAKE_H
#define BRAKE_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define BRAKE_PEDAL_STATUS_FRAME_ID (0x1f4u)
#define BRAKE_BRAKE_STATUS_FRAME_ID (0x1f5u)

/* Frame lengths in bytes. */
#define BRAKE_PEDAL_STATUS_LENGTH (2u)
#define BRAKE_BRAKE_STATUS_LENGTH (1u)

/* Extended or standard frame types. */
#define BRAKE_PEDAL_STATUS_IS_EXTENDED (0)
#define BRAKE_BRAKE_STATUS_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */
#define BRAKE_PEDAL_STATUS_CYCLE_TIME_MS (10u)
#define BRAKE_BRAKE_STATUS_CYCLE_TIME_MS (10u)

/* Signal choices. */


/* Frame Names. */
#define BRAKE_PEDAL_STATUS_NAME "PedalStatus"
#define BRAKE_BRAKE_STATUS_NAME "BrakeStatus"

/* Signal Names. */
#define BRAKE_PEDAL_STATUS_BRAKE_PEDAL_POS_NAME "BrakePedalPos"
#define BRAKE_PEDAL_STATUS_BRAKE_PEDAL_POS_AC_NAME "BrakePedalPos_AC"
#define BRAKE_BRAKE_STATUS_BRAKE_FORCE_NAME "BrakeForce"

/**
 * Signals in message PedalStatus.
 *
 * All signal values are as on the CAN bus.
 */
struct brake_pedal_status_t {
    /**
     * Range: 0..0 (0..1 -)
     * Scale: 1000
     * Offset: 0
     */
    int8_t brake_pedal_pos;

    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    int8_t brake_pedal_pos_ac;
};

/**
 * Signals in message BrakeStatus.
 *
 * All signal values are as on the CAN bus.
 */
struct brake_brake_status_t {
    /**
     * Range: 0..0 (0..1 -)
     * Scale: 1000
     * Offset: 0
     */
    int8_t brake_force;
};

/**
 * Pack message PedalStatus.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int brake_pedal_status_pack(
    uint8_t *dst_p,
    const struct brake_pedal_status_t *src_p,
    size_t size);

/**
 * Unpack message PedalStatus.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int brake_pedal_status_unpack(
    struct brake_pedal_status_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from PedalStatus.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int brake_pedal_status_init(struct brake_pedal_status_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int8_t brake_pedal_status_brake_pedal_pos_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double brake_pedal_status_brake_pedal_pos_decode(int8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool brake_pedal_status_brake_pedal_pos_is_in_range(int8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int8_t brake_pedal_status_brake_pedal_pos_ac_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double brake_pedal_status_brake_pedal_pos_ac_decode(int8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool brake_pedal_status_brake_pedal_pos_ac_is_in_range(int8_t value);

/**
 * Pack message BrakeStatus.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int brake_brake_status_pack(
    uint8_t *dst_p,
    const struct brake_brake_status_t *src_p,
    size_t size);

/**
 * Unpack message BrakeStatus.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int brake_brake_status_unpack(
    struct brake_brake_status_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BrakeStatus.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int brake_brake_status_init(struct brake_brake_status_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int8_t brake_brake_status_brake_force_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double brake_brake_status_brake_force_decode(int8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool brake_brake_status_brake_force_is_in_range(int8_t value);


#ifdef __cplusplus
}
#endif

#endif
