/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 0.1.dev1+g32ca81e Thu Dec 12 04:52:19 2024.
 */

#include <string.h>

#include "brake/brake.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint16_t shift,
    uint8_t mask) {
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint16_t shift,
    uint8_t mask) {
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

int brake_pedal_status_pack(
    uint8_t *dst_p,
    const struct brake_pedal_status_t *src_p,
    size_t size) {
    uint8_t brake_pedal_pos;
    uint8_t brake_pedal_pos_ac;

    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    brake_pedal_pos = (uint8_t)src_p->brake_pedal_pos;
    dst_p[0] |= pack_left_shift_u8(brake_pedal_pos, 0u, 0xffu);
    brake_pedal_pos_ac = (uint8_t)src_p->brake_pedal_pos_ac;
    dst_p[1] |= pack_left_shift_u8(brake_pedal_pos_ac, 0u, 0xffu);

    return (2);
}

int brake_pedal_status_unpack(
    struct brake_pedal_status_t *dst_p,
    const uint8_t *src_p,
    size_t size) {
    uint8_t brake_pedal_pos;
    uint8_t brake_pedal_pos_ac;

    if (size < 2u) {
        return (-EINVAL);
    }

    brake_pedal_pos = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->brake_pedal_pos = (int8_t)brake_pedal_pos;
    brake_pedal_pos_ac = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->brake_pedal_pos_ac = (int8_t)brake_pedal_pos_ac;

    return (0);
}

int brake_pedal_status_init(struct brake_pedal_status_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct brake_pedal_status_t));

    return 0;
}

int8_t brake_pedal_status_brake_pedal_pos_encode(double value) {
    return (int8_t)(value / 1000.0);
}

double brake_pedal_status_brake_pedal_pos_decode(int8_t value) {
    return (static_cast<double>(value) * 1000.0);
}

bool brake_pedal_status_brake_pedal_pos_is_in_range(int8_t value) {
    return ((value >= 0) && (value <= 0));
}

int8_t brake_pedal_status_brake_pedal_pos_ac_encode(double value) {
    return (int8_t)(value);
}

double brake_pedal_status_brake_pedal_pos_ac_decode(int8_t value) {
    return (static_cast<double>(value));
}

bool brake_pedal_status_brake_pedal_pos_ac_is_in_range(int8_t value) {
    return (value >= 0);
}

int brake_brake_status_pack(
    uint8_t *dst_p,
    const struct brake_brake_status_t *src_p,
    size_t size) {
    uint8_t brake_force;

    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    brake_force = (uint8_t)src_p->brake_force;
    dst_p[0] |= pack_left_shift_u8(brake_force, 0u, 0xffu);

    return (1);
}

int brake_brake_status_unpack(
    struct brake_brake_status_t *dst_p,
    const uint8_t *src_p,
    size_t size) {
    uint8_t brake_force;

    if (size < 1u) {
        return (-EINVAL);
    }

    brake_force = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->brake_force = (int8_t)brake_force;

    return (0);
}

int brake_brake_status_init(struct brake_brake_status_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct brake_brake_status_t));

    return 0;
}

int8_t brake_brake_status_brake_force_encode(double value) {
    return (int8_t)(value / 1000.0);
}

double brake_brake_status_brake_force_decode(int8_t value) {
    return (static_cast<double>(value) * 1000.0);
}

bool brake_brake_status_brake_force_is_in_range(int8_t value) {
    return ((value >= 0) && (value <= 0));
}
