/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 0.1.dev1+g32ca81e Thu Dec 12 04:52:57 2024.
 */

#include <string.h>

#include "vehicle/vehicle.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint16_t shift,
    uint8_t mask) {
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint16_t shift,
    uint8_t mask) {
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

int vehicle_engine_status_pack(
    uint8_t *dst_p,
    const struct vehicle_engine_status_t *src_p,
    size_t size) {
    uint8_t check_engine_clear;
    uint8_t check_engine_set;

    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    check_engine_set = (uint8_t)src_p->check_engine_set;
    dst_p[0] |= pack_left_shift_u8(check_engine_set, 0u, 0xffu);
    check_engine_clear = (uint8_t)src_p->check_engine_clear;
    dst_p[1] |= pack_left_shift_u8(check_engine_clear, 0u, 0xffu);

    return (2);
}

int vehicle_engine_status_unpack(
    struct vehicle_engine_status_t *dst_p,
    const uint8_t *src_p,
    size_t size) {
    uint8_t check_engine_clear;
    uint8_t check_engine_set;

    if (size < 2u) {
        return (-EINVAL);
    }

    check_engine_set = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->check_engine_set = (int8_t)check_engine_set;
    check_engine_clear = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->check_engine_clear = (int8_t)check_engine_clear;

    return (0);
}

int vehicle_engine_status_init(struct vehicle_engine_status_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct vehicle_engine_status_t));

    return 0;
}

int8_t vehicle_engine_status_check_engine_set_encode(double value) {
    return (int8_t)(value);
}

double vehicle_engine_status_check_engine_set_decode(int8_t value) {
    return (static_cast<double>(value));
}

bool vehicle_engine_status_check_engine_set_is_in_range(int8_t value) {
    return (value >= 0);
}

int8_t vehicle_engine_status_check_engine_clear_encode(double value) {
    return (int8_t)(value);
}

double vehicle_engine_status_check_engine_clear_decode(int8_t value) {
    return (static_cast<double>(value));
}

bool vehicle_engine_status_check_engine_clear_is_in_range(int8_t value) {
    return (value >= 0);
}
